apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mime-api
  namespace: mime-api
  labels:
    app: mime-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /mime-api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mime-api
                port:
                  number: 80