apiVersion: v1
kind: Service
metadata:
  name: mime-api
  namespace: mime-api
  labels:
    app: mime-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: mime-api