// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: proto/displaypart.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DisplayPartService_ExtractDisplayPart_FullMethodName       = "/displaypart.DisplayPartService/ExtractDisplayPart"
	DisplayPartService_ExtractDisplayPartStream_FullMethodName = "/displaypart.DisplayPartService/ExtractDisplayPartStream"
	DisplayPartService_Health_FullMethodName                   = "/displaypart.DisplayPartService/Health"
)

// DisplayPartServiceClient is the client API for DisplayPartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisplayPartServiceClient interface {
	ExtractDisplayPart(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
	ExtractDisplayPartStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, ExtractResponse], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type displayPartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDisplayPartServiceClient(cc grpc.ClientConnInterface) DisplayPartServiceClient {
	return &displayPartServiceClient{cc}
}

func (c *displayPartServiceClient) ExtractDisplayPart(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, DisplayPartService_ExtractDisplayPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayPartServiceClient) ExtractDisplayPartStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, ExtractResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DisplayPartService_ServiceDesc.Streams[0], DisplayPartService_ExtractDisplayPartStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, ExtractResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DisplayPartService_ExtractDisplayPartStreamClient = grpc.ClientStreamingClient[FileChunk, ExtractResponse]

func (c *displayPartServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DisplayPartService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisplayPartServiceServer is the server API for DisplayPartService service.
// All implementations must embed UnimplementedDisplayPartServiceServer
// for forward compatibility.
type DisplayPartServiceServer interface {
	ExtractDisplayPart(context.Context, *ExtractRequest) (*ExtractResponse, error)
	ExtractDisplayPartStream(grpc.ClientStreamingServer[FileChunk, ExtractResponse]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedDisplayPartServiceServer()
}

// UnimplementedDisplayPartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDisplayPartServiceServer struct{}

func (UnimplementedDisplayPartServiceServer) ExtractDisplayPart(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractDisplayPart not implemented")
}
func (UnimplementedDisplayPartServiceServer) ExtractDisplayPartStream(grpc.ClientStreamingServer[FileChunk, ExtractResponse]) error {
	return status.Error(codes.Unimplemented, "method ExtractDisplayPartStream not implemented")
}
func (UnimplementedDisplayPartServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDisplayPartServiceServer) mustEmbedUnimplementedDisplayPartServiceServer() {}
func (UnimplementedDisplayPartServiceServer) testEmbeddedByValue()                            {}

// UnsafeDisplayPartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisplayPartServiceServer will
// result in compilation errors.
type UnsafeDisplayPartServiceServer interface {
	mustEmbedUnimplementedDisplayPartServiceServer()
}

func RegisterDisplayPartServiceServer(s grpc.ServiceRegistrar, srv DisplayPartServiceServer) {
	// If the following call panics, it indicates UnimplementedDisplayPartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DisplayPartService_ServiceDesc, srv)
}

func _DisplayPartService_ExtractDisplayPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayPartServiceServer).ExtractDisplayPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DisplayPartService_ExtractDisplayPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayPartServiceServer).ExtractDisplayPart(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DisplayPartService_ExtractDisplayPartStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DisplayPartServiceServer).ExtractDisplayPartStream(&grpc.GenericServerStream[FileChunk, ExtractResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DisplayPartService_ExtractDisplayPartStreamServer = grpc.ClientStreamingServer[FileChunk, ExtractResponse]

func _DisplayPartService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayPartServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DisplayPartService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayPartServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DisplayPartService_ServiceDesc is the grpc.ServiceDesc for DisplayPartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DisplayPartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "displaypart.DisplayPartService",
	HandlerType: (*DisplayPartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractDisplayPart",
			Handler:    _DisplayPartService_ExtractDisplayPart_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DisplayPartService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExtractDisplayPartStream",
			Handler:       _DisplayPartService_ExtractDisplayPartStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/displaypart.proto",
}
