// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: proto/displaypart.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmlContent    []byte                 `protobuf:"bytes,1,opt,name=eml_content,json=emlContent,proto3" json:"eml_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_proto_displaypart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_displaypart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_proto_displaypart_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetEmlContent() []byte {
	if x != nil {
		return x.EmlContent
	}
	return nil
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_proto_displaypart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_displaypart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_proto_displaypart_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExtractResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExtractResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_displaypart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_displaypart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_displaypart_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_displaypart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_displaypart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_displaypart_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_displaypart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_displaypart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_displaypart_proto_rawDescGZIP(), []int{4}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_displaypart_proto protoreflect.FileDescriptor

const file_proto_displaypart_proto_rawDesc = "" +
	"\n" +
	"\x17proto/displaypart.proto\x12\vdisplaypart\"1\n" +
	"\x0eExtractRequest\x12\x1f\n" +
	"\veml_content\x18\x01 \x01(\fR\n" +
	"emlContent\"d\n" +
	"\x0fExtractResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xfc\x01\n" +
	"\x12DisplayPartService\x12O\n" +
	"\x12ExtractDisplayPart\x12\x1b.displaypart.ExtractRequest\x1a\x1c.displaypart.ExtractResponse\x12R\n" +
	"\x18ExtractDisplayPartStream\x12\x16.displaypart.FileChunk\x1a\x1c.displaypart.ExtractResponse(\x01\x12A\n" +
	"\x06Health\x12\x1a.displaypart.HealthRequest\x1a\x1b.displaypart.HealthResponseB\x10Z\x0emime_api/protob\x06proto3"

var (
	file_proto_displaypart_proto_rawDescOnce sync.Once
	file_proto_displaypart_proto_rawDescData []byte
)

func file_proto_displaypart_proto_rawDescGZIP() []byte {
	file_proto_displaypart_proto_rawDescOnce.Do(func() {
		file_proto_displaypart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_displaypart_proto_rawDesc), len(file_proto_displaypart_proto_rawDesc)))
	})
	return file_proto_displaypart_proto_rawDescData
}

var file_proto_displaypart_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_displaypart_proto_goTypes = []any{
	(*ExtractRequest)(nil),  // 0: displaypart.ExtractRequest
	(*ExtractResponse)(nil), // 1: displaypart.ExtractResponse
	(*HealthRequest)(nil),   // 2: displaypart.HealthRequest
	(*HealthResponse)(nil),  // 3: displaypart.HealthResponse
	(*FileChunk)(nil),       // 4: displaypart.FileChunk
}
var file_proto_displaypart_proto_depIdxs = []int32{
	0, // 0: displaypart.DisplayPartService.ExtractDisplayPart:input_type -> displaypart.ExtractRequest
	4, // 1: displaypart.DisplayPartService.ExtractDisplayPartStream:input_type -> displaypart.FileChunk
	2, // 2: displaypart.DisplayPartService.Health:input_type -> displaypart.HealthRequest
	1, // 3: displaypart.DisplayPartService.ExtractDisplayPart:output_type -> displaypart.ExtractResponse
	1, // 4: displaypart.DisplayPartService.ExtractDisplayPartStream:output_type -> displaypart.ExtractResponse
	3, // 5: displaypart.DisplayPartService.Health:output_type -> displaypart.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_displaypart_proto_init() }
func file_proto_displaypart_proto_init() {
	if File_proto_displaypart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_displaypart_proto_rawDesc), len(file_proto_displaypart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_displaypart_proto_goTypes,
		DependencyIndexes: file_proto_displaypart_proto_depIdxs,
		MessageInfos:      file_proto_displaypart_proto_msgTypes,
	}.Build()
	File_proto_displaypart_proto = out.File
	file_proto_displaypart_proto_goTypes = nil
	file_proto_displaypart_proto_depIdxs = nil
}
